hw05
================
ziqiangt
2018/10/16

-   [Overview](#overview)
-   [The Assignment](#the-assignment)
    -   [Part 1: Factor management](#part-1-factor-management)
    -   [Reorder the levels of country and continent](#reorder-the-levels-of-country-and-continent)
    -   [Part 2: File I/O](#part-2-file-io)
    -   [Part 3: Visualization design](#part-3-visualization-design)
    -   [Part 4: Writing figures to file](#part-4-writing-figures-to-file)
    -   [But I want to do more!](#but-i-want-to-do-more)

Overview
--------

Goals:

-   Reorder a factor in a principled way based on the data and demonstrate the effect in arranged data and in figures.
-   Write some data to file and load it back into R.
-   Improve a figure (or make one from scratch), using new knowledge, e.g., control the color scheme, use factor levels, smoother mechanics.
-   Make a plotly visual.
-   Implement visualization design principles.

let's first library all dataset:

``` r
library(gapminder)
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.2.1 --

    ## <U+221A> ggplot2 3.0.0     <U+221A> purrr   0.2.5
    ## <U+221A> tibble  1.4.2     <U+221A> dplyr   0.7.6
    ## <U+221A> tidyr   0.8.1     <U+221A> stringr 1.3.1
    ## <U+221A> readr   1.1.1     <U+221A> forcats 0.3.0

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(knitr)
library(plotly)
```

    ## 
    ## Attaching package: 'plotly'

    ## The following object is masked from 'package:ggplot2':
    ## 
    ##     last_plot

    ## The following object is masked from 'package:stats':
    ## 
    ##     filter

    ## The following object is masked from 'package:graphics':
    ## 
    ##     layout

``` r
suppressPackageStartupMessages(library(tidyverse))
library(scales)
```

    ## 
    ## Attaching package: 'scales'

    ## The following object is masked from 'package:purrr':
    ## 
    ##     discard

    ## The following object is masked from 'package:readr':
    ## 
    ##     col_factor

The Assignment
--------------

### Part 1: Factor management

| Function        | Definition                              |
|-----------------|-----------------------------------------|
| `droplevels()`  | drop unused levels                      |
| `arrange()`     | no effects on the order of levels pairs |
| `fct_reorcer()` | affect on the order of levels pairs     |

#### Before drop Oceania

let's first view the structure of the dataset:

``` r
gapminder %>% 
  summarize(
    nrow = nrow(gapminder),
    nlevels = nlevels(gapminder$country),
    nlevels2 = nlevels(gapminder$continent)) %>% 
  knitr::kable(col.names = c("Rows", "Levels of country", "Levels of continent"))
```

|  Rows|  Levels of country|  Levels of continent|
|-----:|------------------:|--------------------:|
|  1704|                142|                    5|

It can be seen that the total number of rows in the data.frame is 1704. 'Country' and 'continent' are both factors with 142 and 5 levels respectively.

#### Drop Oceania;

``` r
no_oceania <- gapminder %>%
  filter(continent != "Oceania") # filter the Oceania
  
no_oceania %>% 
  summarize(
    nrow = nrow(no_oceania),
    nlevels = nlevels(no_oceania$country),
    nlevels2 = nlevels(no_oceania$continent)) %>% 
  knitr::kable(col.names = c("Rows_filtered", "Levels of country_filtered", "Levels of continent_filtered"))
```

|  Rows\_filtered|  Levels of country\_filtered|  Levels of continent\_filtered|
|---------------:|----------------------------:|------------------------------:|
|            1680|                          142|                              5|

It can be seen that the total number of rows in the data.frame has droped from the orginal 1704 to 1680. However, the levels was not droped. Therefore, we need to investigate the function 'droplevels()'.

``` r
no_oceania_drop_level <- no_oceania %>%
  droplevels()

no_oceania_drop_level %>% 
  summarize(
    nrow = nrow(no_oceania_drop_level),
    nlevels = nlevels(no_oceania_drop_level$country),
    nlevels2 = nlevels(no_oceania_drop_level$continent)) %>% 
  knitr::kable(col.names = c("Rows_drop", "Levels of country_drop", "Levels of continent_drop"))
```

|  Rows\_drop|  Levels of country\_drop|  Levels of continent\_drop|
|-----------:|------------------------:|--------------------------:|
|        1680|                      140|                          4|

It can be seen that the levels has droped from the orginal 1704 to 1680. However, the levels 'country' and 'continent' has been droped to 140 (originally 142) and 4 (originally 5) levels respectively.

With the help of mutate, we could restrict which levels to drop.

``` r
no_oceania_fct_drop <- no_oceania %>%
  mutate(continent = droplevels(continent))

no_oceania_drop_level %>% 
  summarize(
    nrow = nrow(no_oceania_fct_drop),
    nlevels = nlevels(no_oceania_fct_drop$country),
    nlevels2 = nlevels(no_oceania_fct_drop$continent)) %>% 
  knitr::kable(col.names = c("Rows_drop", "Levels of country_drop", "Levels of continent_drop"))
```

|  Rows\_drop|  Levels of country\_drop|  Levels of continent\_drop|
|-----------:|------------------------:|--------------------------:|
|        1680|                      142|                          4|

### Reorder the levels of country and continent

#### the effects of arrange

``` r
before_arrange <- gapminder %>%
  filter(continent == "Americas") %>% 
  group_by(country) %>% 
  mutate(max_life = max(lifeExp)) %>% # calcuate maximum lifeExp for each country
  select(country, max_life) %>% 
  unique() # delete the repeat rows

kable(head( before_arrange, 10 )) # view the first 10 rows
```

| country            |  max\_life|
|:-------------------|----------:|
| Argentina          |     75.320|
| Bolivia            |     65.554|
| Brazil             |     72.390|
| Canada             |     80.653|
| Chile              |     78.553|
| Colombia           |     72.889|
| Costa Rica         |     78.782|
| Cuba               |     78.273|
| Dominican Republic |     72.235|
| Ecuador            |     74.994|

#### the effects of arrange

``` r
after_arrange <- before_arrange %>% 
  arrange(max_life)

kable(head( after_arrange, 10 )) # view the first 10 rows
```

| country             |  max\_life|
|:--------------------|----------:|
| Haiti               |     60.916|
| Bolivia             |     65.554|
| Trinidad and Tobago |     69.862|
| Honduras            |     70.198|
| Guatemala           |     70.259|
| Peru                |     71.421|
| Paraguay            |     71.752|
| El Salvador         |     71.878|
| Dominican Republic  |     72.235|
| Brazil              |     72.390|

It can be seen that the arrange does have effect on table. But how about the figures?

``` r
before_arrange %>% 
  ggplot( aes( x = max_life, y = country, color = country )) +
  geom_point() +
  ggtitle( "Before arrange" ) +
  xlab( "Max life expantancy") +
  ylab( "Country" ) +
  theme_bw()  #change theme
```

![](hw05_files/figure-markdown_github/unnamed-chunk-8-1.png)

``` r
after_arrange %>% 
  ggplot( aes( x = max_life, y = country, color = country )) +
  geom_point() +
  ggtitle( "After arrange" ) +
  xlab( "Max life expantancy") +
  ylab( "Country" ) +
  theme_gray()  #change theme
```

![](hw05_files/figure-markdown_github/unnamed-chunk-8-2.png)

It is easily can be seen that the arrange has no effect on figures. Let us try the fucntion fct\_reorder().

``` r
before_arrange %>% 
  ggplot( aes( x = max_life, y = fct_reorder(country, max_life), color = country )) +
  geom_point() +
  ggtitle( "After fct_reorder" ) +
  xlab( "Max life expantancy") +
  ylab( "Country" ) +
  theme_dark()  #change theme
```

![](hw05_files/figure-markdown_github/unnamed-chunk-9-1.png)

Conclusions: using arrange() along will not affect the order of levels while fct\_reorcer() does.

### Part 2: File I/O

<table style="width:50%;">
<colgroup>
<col width="23%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>write_csv()/read_csv()</code></td>
<td>Write/Read a data frame to a delimited file while parse each column with default formats</td>
</tr>
<tr class="even">
<td><code>saveRDS()/readRDS()</code></td>
<td>Write/Read a single R object to a file and keep the original formats</td>
</tr>
<tr class="odd">
<td><code>dput()/dget()</code></td>
<td>Writes/Read an ASCII text representation of an R object to a file and keep the original formats</td>
</tr>
</tbody>
</table>

Let's example the part 1 data with the above functions. First, let's recall the dataset- before\_arrange:

``` r
kable( head( before_arrange, 10 )) 
```

| country            |  max\_life|
|:-------------------|----------:|
| Argentina          |     75.320|
| Bolivia            |     65.554|
| Brazil             |     72.390|
| Canada             |     80.653|
| Chile              |     78.553|
| Colombia           |     72.889|
| Costa Rica         |     78.782|
| Cuba               |     78.273|
| Dominican Republic |     72.235|
| Ecuador            |     74.994|

``` r
glimpse( before_arrange) # just for learning the function glimpse
```

    ## Observations: 25
    ## Variables: 2
    ## $ country  <fct> Argentina, Bolivia, Brazil, Canada, Chile, Colombia, ...
    ## $ max_life <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.78...

#### write\_csv()/read\_csv()

``` r
write_csv(before_arrange, "data_csv.csv") # write to csv
read_data_csv <- read_csv("data_csv.csv") # read from csv
```

    ## Parsed with column specification:
    ## cols(
    ##   country = col_character(),
    ##   max_life = col_double()
    ## )

``` r
read_back <- glimpse(read_data_csv) 
```

    ## Observations: 25
    ## Variables: 2
    ## $ country  <chr> "Argentina", "Bolivia", "Brazil", "Canada", "Chile", ...
    ## $ max_life <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.78...

``` r
if(read_data_csv == before_arrange) # judge the store data is correct or not
  ("Read back data Match with data before storing!")
```

    ## Warning in if (read_data_csv == before_arrange) ("Read back data Match with
    ## data before storing!"): the condition has length > 1 and only the first
    ## element will be used

    ## [1] "Read back data Match with data before storing!"

It should be noted that after read\_csv, the class of country has changed from the original <fct> to <chr> while the if cannot distinguish this difference.

#### saveRDS()/readRDS()

``` r
saveRDS(before_arrange, "data_csv.csv") # write to csv
read_data_RDS <- readRDS("data_csv.csv") # read from csv
glimpse(read_data_RDS) 
```

    ## Observations: 25
    ## Variables: 2
    ## $ country  <fct> Argentina, Bolivia, Brazil, Canada, Chile, Colombia, ...
    ## $ max_life <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.78...

By using saveRDS()/readRDS(), the class can be kept to be the same as the original format.

#### dput()/dget()

``` r
dput(before_arrange, "data_csv.csv") # write to csv
read_data_dget <- dget("data_csv.csv") # read from csv
glimpse(read_data_dget) 
```

    ## Observations: 25
    ## Variables: 2
    ## $ country  <fct> Argentina, Bolivia, Brazil, Canada, Chile, Colombia, ...
    ## $ max_life <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.78...

Similarly as saveRDS()/readRDS(), the class can be kept to be the same as the original format.

### Part 3: Visualization design

Here is what I did in assignment 03. I want to show the maximum and minimum of GDP per capital for all continents.

``` r
GDP_per_cap <- gapminder %>% 
  group_by( continent ) %>% 
  summarize( minGDP = min( gdpPercap ),
            maxGDP = max( gdpPercap ))
GDP_per_cap %>% 
gather( key = min_or_max, value = GDP_per_cap, 2:3 ) %>%  
  ggplot( aes( x = continent, y = GDP_per_cap, fill = continent )) +
  geom_col( alpha = 0.5 ) +
  scale_y_log10() +
  facet_wrap( .~min_or_max )  +
  ggtitle( "The GDP per capital for all continents" ) +
  xlab( "Continent") +
  ylab( "GDP per capital" )
```

![](hw05_files/figure-markdown_github/unnamed-chunk-14-1.png)

It can seen the y-axis is reall hard to know the exact meaning. Therefore, let's change to dollar\_format(). Besides, we could change the strip.background to have a more clear view. Moreover, the test size could also be ajusted.

``` r
Df_GDP_per_cap <- gapminder %>% 
  group_by( continent ) %>% 
  summarize( minGDP = min( gdpPercap ),
            maxGDP = max( gdpPercap ))

plot_new <- Df_GDP_per_cap %>% 
gather( key = min_or_max, value = Df_GDP_per_cap, 2:3 ) %>%  
  ggplot( aes( x = continent, y = Df_GDP_per_cap, fill = continent )) +
  geom_col( alpha = 0.5 ) +
  scale_y_log10(labels=dollar_format()) + #change to dollar format
  facet_wrap( .~min_or_max )  +
  ggtitle( "The GDP per capital for all continents" ) +
  xlab( "Continent") +
  ylab( "GDP per capital" ) +
  theme_dark() +                          #change theme 
  theme(axis.text =  element_text(size = 12),
          strip.background = element_rect(fill = "orange"))

plot_new
```

![](hw05_files/figure-markdown_github/unnamed-chunk-15-1.png)

plotly VS ggplot: Plotly and ggplot2 are inherently for different purposes. plotly allows you to quickly create beautiful, reactive D3 plots that are particularly powerful in websites and dashboards. You can hover your mouse over the plots and see the data values, zoom in and out of specific regions, and capture stills.

``` r
#ggplotly(plot_new)
#api_create(plot_new, filename = "plotly_new")
```

#### try to look at my plotly file on this link:

[plot\_new](https://plot.ly/~wdckp520/3/#/)

### Part 4: Writing figures to file

``` r
ggsave("plot_new.png", plot_new, width=50, height=30, units = "cm", dpi = 300)
```

#### load figure

![plot\_new.png](./plot_new.png)

### But I want to do more!

In this task, I want to add the food for those five countries:

``` r
country_food <- 
  data.frame(
  country = c("China","Italy", "Spain", "Japan","Canada"),
  food = c("Hot pot","Pizza","Seafood Paella","Udon noodle","Ice wine"))

sub_gapminder <- gapminder %>%
  filter( country %in% c("China","Italy", "Spain", "Japan","Canada")) %>% 
  droplevels() 


subgapminder.add.food <- left_join(sub_gapminder,country_food)
```

    ## Joining, by = "country"

Let's view the levels:

``` r
subgapminder.add.food %>% 
  summarize(
    nrow = nrow(subgapminder.add.food),
    nlevels = nlevels(subgapminder.add.food$country),
    nlevels2 = nlevels(subgapminder.add.food$food)) %>% 
  knitr::kable(col.names = c("Rows", "Levels of country", "Levels of food"))
```

|  Rows|  Levels of country|  Levels of food|
|-----:|------------------:|---------------:|
|    60|                  5|               5|

It can be seen that there are 5 levels of both country and foods.
